apiVersion: skaffold/v1beta15
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: blockchain-ignite-node
      context: .
      jib:
        args: ["-DskipTests=true"]
        project: ""
deploy:
  kubectl:
    manifests:
      - .kubernetes-manifests/**.yml
profiles:
  - name: dockerfile
    build:
      artifacts:
        - image: blockchain-ignite-node
