apiVersion: v1
kind: Service
metadata:
  name: ignite-server-service
spec:
  selector:
    app: ignite-server
  ports:
    - name: tpc
      port: 7331
      targetPort: 7331
      protocol: TCP
    - name: api
      port: 2020
      targetPort: 2020
  type: LoadBalancer
